### ISSUE TITLE
Make Rancher/cli static

### ISSUE THREAD

**Issue by dantebarba** [badouralix/dockerfiles#3]
I was trying to run this [example](https://gitlab.com/janpoboril/docker-working-examples/blob/master/gitlab-ci-with-rancher/.gitlab-ci.yml), but I found that you are always using the rancher/cli:latest, which now is on Rancher 2.0. I'm currently using Rancher 1.6, can you push rancher 2.0 
 and rancher 1.6 tags?

**Comment by dantebarba** [comment]
Forked the project and created an image referencing rancher-cli v1.0.0 which is the version for Rancher 1.x. You can access it by using dantebarba/rancher-cli:v1.0.0.

**Comment by badouralix** [comment]
Cool, thanks! Otherwise, even though the Dockerfile is using `latest`, it actually refers to the latest image built by `rancher/cli`, which can be v2.x or v0.6.x. They are properly tagged via a hook, and appear here: https://hub.docker.com/r/badouralix/rancher-cli/tags/

**Comment by dantebarba** [comment]
Yes looks like rancher-cli version 1.x.x is for rancher 2.x too, so I changed the image to be fixed on rancher-cli 0.6.4. Now it's working correctly on gitlab-ci. 👍
