### ISSUE TITLE
rancher-cli Segmentation Fault

### ISSUE THREAD

**Issue by jamespedid** [badouralix/dockerfiles#4]
I'm getting this issue when trying to run commands with the image.

![image](https://user-images.githubusercontent.com/1280555/70462097-28c38c80-1a88-11ea-8802-b885611afa14.png)

**Comment by badouralix** [comment]
Hey @jamespedid, just saw your issue, did you figure out what the problem was ?

**Comment by jamespedid** [comment]
I ended up just making my own image with the version of the rancher-cli that was suggested by my rancher version. (There's a little button in the corner of the rancher ui.) I added that and kubectl and node to the image and used node for mustache templating.
