### ISSUE TITLE
Additional functionality for use of arrays

### ISSUE THREAD

**Issue by m4ttr33d** [badouralix/dockerfiles#5]
Currently, I am unable to use arrays in the same script as jq and curl - see following code - 

```
for k in $(jq '.item | keys | .[]' $JSON_FILE); do
	NAME=$(jq -r ".item[$k] .name" $JSON_FILE)
	URL=$(jq -r ".item[$k] .request .url" $JSON_FILE)
	REQUEST_TYPE=$(jq -r ".item[$k] .request .method" $JSON_FILE)
	HEADER_LIST=() #fails here
	for h in $(jq -r ".item[$k] .request .header | keys | .[]" $JSON_FILE); do
		HEADER_KEY=$(jq -r ".item[$k] .request .header[$h] .key" $JSON_FILE)
		HEADER_VALUE=$(jq -r ".item[$k] .request .header[$h] .value" $JSON_FILE)
		HEADER_LIST+=("--header '$HEADER_KEY:$HEADER_VALUE'") # fails here
	done
HEADERS=${HEADER_LIST[@]} #expecing failure here
```

Failures on array lists as above, is there support for this?

**Comment by badouralix** [comment]
Hi @m4ttr33d !

Just to be clear, this is a script running within a `badouralix/curl-jq` container, right ?

The current image is built off `alpine`, thus running on `/bin/sh` which does not support arrays

```bash
$ docker run -it --rm badouralix/curl-jq /bin/sh
/ # HEADER_LIST=()
/bin/sh: syntax error: unexpected "("
```

Let me see if I can ship an image based off `debian` instead, with `/bin/bash` instead of `/bin/sh`

**Comment by m4ttr33d** [comment]
Hi @badouralix! Thank you so much for getting back to me so quick! That makes sense. I guess I should have provided a little more context - this is a script running in a Concourse container. Thank you for the quick response, that would be awesome, let me know if I can help at all. I would have forked the repo and done it but I’m still coming up to speed on how to compose docker containers. Thank you, I appreciate your help!

**Comment by badouralix** [comment]
Alright I added a new image tag with https://github.com/badouralix/dockerfiles/commit/4edac436cfe1fbb04054dfec4b43d4e7bf5aba60

Can you try with `badouralix/curl-jq:debian` ? Your script should work just fine with this new image

```bash
$ docker run -it --rm badouralix/curl-jq:debian /bin/bash
root@314027d96909:/# HEADER_LIST=()
root@314027d96909:/# echo $?
0
```

**Comment by m4ttr33d** [comment]
Almost, I think we're on the right track. I should have mentioned I'm cloning this docker container and running it in Concourse. This was the only repository that I was able to find that allowed me to run jq and curl, so I'm a little restricted. When I try to run it with the :debian on there, I get the following - ```resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to construct named reference: invalid reference format```

**Comment by m4ttr33d** [comment]
Worked like a charm, thank you much! I had the syntax incorrect when I was testing, but once I got that, I was able to get it. Thanks for your quick help! I appreciate it! Let me know if I can do anything in return.
